server:
 port: 8083
Spring:
 datasource: 
  url: jdbc:mysql://localhost:3306/studentEureka
  username: root
  password: 1234
  driver-class-name: com.mysql.jdbc.Driver 
 jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true
spring:
  application:
    name: school-service  

  
  